services:
  neotavern-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: neotavern-frontend
    container_name: neotavern-frontend
    restart: unless-stopped
    ports:
      - '4173:4173'
    environment:
      - PUID=1000
      - PGID=1000
      # If your SillyTavern is on a different port, change it here:
      - BACKEND_PORT=8000
    # This magic section makes 'host.docker.internal' work on Linux
    extra_hosts:
      - 'host.docker.internal:host-gateway'
